env:
  - ONTRAVIS=True
language: python
python:
  - "3.6"
  - "3.5"
  - "2.7"

# install
install:
  - pip install jupyter
  - python setup.py install

# run
script:
  - pytest
  - for nb in serpentTools/examples/*ipynb; do ;jupyter nbconvert --execute $nb; done
