"""
Parser that reads history files

Files can be generated by adding ``set his 1`` to the input 
file

"""

from numpy import empty, asfortranarray

from serpentTools.objects.readers import BaseReader
from serpentTools.engines import KeywordParser


class HistoryReader(BaseReader):

    def __init__(self, filePath):
        BaseReader.__init__(self, filePath, 'history')
        self.arrays = {}
        self.numInactive = None

    def __getitem__(self, key):
        return self.arrays[key]

    def _precheck(self):
        with open(self.filePath) as check:
            for line in check:
                if line[:3] == 'HIS':
                    return
        

    def _read(self):
        keys

