readers:
  # settings for each reader to share
  # can add things like verbosity here
  depletion:
    # settings for the depletion reader
      metadataKeys: !!python/object:serpentTools.settings.loaders.DefaultSetting
        name: metadataKeys
        description: Non-material data to store, i.e. zai, names, days, etc.
        default: &mKeysOpts
          ['ZAI', 'NAMES', 'DAYS', 'BU']
        options: *mKeysOpts
      materialVariables: !!python/object:serpentTools.settings.loaders.DefaultSetting
        name: materialVariables
        description: Variables to store on the material objects, i.e. volume, adens, mdens, burnup, etc.
        default: ['VOLUME', 'ADENS', 'MDENS', 'BURNUP']
      materials: !!python/object:serpentTools.settings.loaders.DefaultSetting
        name: materials
        description: Names of materials to store. Empty list == all materials
        default: []